# Using Python for Research Homework: Week 2

In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe (noughts and crosses) simulator and evaluate basic winning strategies.

### Exercise 1

Tic-tac-toe (or noughts and crosses) is a simple strategy game in which two players take turns placing a mark on a 3x3 board, attempting to make a row, column, or diagonal of three with their mark. In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe simulator and evaluate basic winning strategies.

In the following exercises, we will learn to create a tic-tac-toe board, place markers on the board, evaluate if either player has won, and use this to simulate two basic strategies.

#### Instructions 

- For our tic-tac-toe board, we will use a numpy array with dimension 3 by 3. 
- Make a function `create_board()` that creates such a board with the value of each cell set to the integer `0`.
- Call `create_board()` and store it.

In [1]:
# write your code here!
import numpy as np

def create_board():
    board = np.zeros((3,3), dtype=int)
    return board 

create_board()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Exercise 2

Players 1 and 2 will take turns changing values of this array from a 0 to a 1 or 2, indicating the number of the player who places a marker there.

#### Instructions 

- Create a function `place(board, player, position)`, where:
    - `player` is the current player (an integer 1 or 2).
    - `position` is a tuple of length 2 specifying a desired location to place their marker.
    - Your function should only allow the current player to place a marker on the board (change the board position to their number) if that position is empty (zero).
- Use `create_board()` to store a board as `board`, and use `place` to have Player 1 place a marker on location `(0, 0)`.

In [2]:
# write your code here!

board = create_board()

def place(board, player, position):
    if board[position] == 0: # if the position on the board is empty
        board[position] = player # then change the position on the board equal to player's number
        return board 

place(board, 1, (0,0)) # location of the board is specified in the input (0,0), notice we used placed as well


array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Exercise 3

In this exercise, we will determine which positions are available to either player for placing their marker.

#### Instructions 
- Create a function `possibilities(board)` that returns a list of all positions (tuples) on the board that are not occupied (0). (Hint: `numpy.where` is a handy function that returns a list of indices that meet a condition.)
- `board` is already defined from previous exercises. Call `possibilities(board)` to see what it returns!

In [3]:
a = np.random.randn(2, 3)
a

array([[-1.07112335,  0.37534213, -0.37572241],
       [-1.51136805,  1.02155621, -0.63112434]])

In [4]:
b = np.where(a > 0, 1, 0) # if a > 0 print 1 otherwise print 0. 
b

array([[0, 1, 0],
       [0, 1, 0]])

In [5]:
b = np.where(a > 0)
b # row 1, column 1 satisfy the condition

(array([0, 1], dtype=int64), array([1, 1], dtype=int64))

In [6]:
board

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
np.where(board == 0)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [8]:
# write your code here!

def possibilities(board):
    empty = np.where(board == 0)
    return list(zip(empty[0], empty[1])) # puts together coordinates and lists them

possibilities(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

### Exercise 4

The next step is for the current player to place a marker among the available positions. In this exercise, we will select an available board position at random and place a marker there.

#### Instructions 

- Write a function `random_place(board, player)` that places a marker for the current player at random among all the available positions (those currently set to 0).
    - Find possible placements with `possibilities(board)`.
    - Select one possible placement at random using `random.choice(selection)`.
- `board` is already defined from previous exercises. Call `random_place(board, player)` to place a random marker for Player 2, and store this as board to update its value.

In [9]:
import random 

random.choice(possibilities(board))

(2, 0)

In [10]:
possibilities(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [11]:
import random 
random.seed(1)

# write your code here!

def random_place(board, player):
    selections = possibilities(board) # all coordinates of the board available
    if len(selections) > 0: # if there is more than one coordinate to choose from, from the list 
        selection = random.choice(possibilities(board)) # select one at random
        place(board, player, selection) # use previous place function, and include the randomly selected coordinate (selection)
    return board # return the update board, with the updated selections

random_place(board, 2)
   

array([[1, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

### Exercise 5

We will now have both players place three markers each.

#### Instructions 

- A new `board` is already given. Call `random_place(board, player)` to place three pieces each on board for players 1 and 2.
- Print board to see your result.

In [12]:
random.seed(1)
board = create_board()

# write your code here!

board

random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)
random_place(board, 1)
random_place(board, 2)

array([[2, 2, 1],
       [0, 1, 0],
       [0, 1, 2]])

In [30]:
#alternates

for i in range(2):
    for person in [1,2]:
        print(person)


1
2
1
2


In [13]:
# or a more elegant way: 

random.seed(1)
board = create_board()

for i in range(3): # remember this is 0 1 2 or still three turns
    for player in [1, 2]: # this alternates
        random_place(board, player)
board


array([[2, 2, 1],
       [0, 1, 0],
       [0, 1, 2]])

### Exercise 6

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Make a function `row_win(board, player)` that takes the player (integer) and determines if any row consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `row_win` to check if Player 1 has a complete row.

In [14]:
board

array([[2, 2, 1],
       [0, 1, 0],
       [0, 1, 2]])

In [15]:
np.all(board==player, axis=1) # in all of the board, or in all 3 rows is there any where all are ones or all are two's

array([False, False, False])

In [16]:
np.all(board==player, axis=0)

array([False, False, False])

In [17]:
# write your code here!

def row_win(board,player):
    if np.any(np.all(board==player, axis=1)):# this checks if any row contains all positions equal to player.
        return True
    else:
        return False
    
row_win(board,1)

False

### Exercise 7

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Make a function `col_win(board, player)` that takes the player (integer) and determines if any column consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `col_win` to check if Player 1 has a complete row.

In [18]:
# write your code here! 

def col_win(board,player):
    if np.any(np.all(board==player, axis=0)):# this checks if any column contains all positions equal to player.
        return True
    else:
        return False
    
row_win(board,1)

False

### Exercise 8

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Finally, create a function `diag_win(board, player)` that tests if either diagonal of the board consists of only their marker. Have it return `True` if this condition is met, and `False` otherwise.
- `board` has been slightly modified from a previous exercise. Call `diag_win` to check if Player 2 has a complete diagonal.

In [19]:
board[1,1] = 2 # here they change the board middle number to 2,

# write your code here!

def diag_win(board,player):
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        return True
    else:
        return False

diag_win(board, 2)

# np.diag returns the diagonal of the array
# np.fliplr rearranges columns in reverse order

True

### Exercise 9

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Create a function `evaluate(board)` that uses `row_win`, `col_win`, and `diag_win` functions for both players. If one of them has won, return that player's number. If the board is full but no one has won, return -1. Otherwise, return 0.
- `board` is already defined from previous exercises. Call evaluate to see if either player has won the game yet.

In [20]:
board

array([[2, 2, 1],
       [0, 2, 0],
       [0, 1, 2]])

In [21]:
def evaluate(board):
    winner = 0 # start with a zero value, this is late replaced by player
    for player in [1, 2]: # alternate between players
        if row_win(board, player) or col_win(board, player) or diag_win(board, player): # did not know I could use or for if sta
            winner = player # winner is reassigned to player
    if np.all(board != 0) and winner == 0: # once none of the values on the board are not equal to zero(meaning either 1 or 2) and winner is not reassigned (still 0) since there is no winner
        winner = -1 # reassigned winner to -1, meaning a tie
    return winner

evaluate(board)

2

### Exercise 10

In this exercise, we will use all the functions we have made to simulate an entire game.

#### Instructions 

- `create_board()`, `random_place(board, player)`, and `evaluate(board)` have been created in previous exercises. Create a function `play_game()` that:
    - Creates a board.
    - Alternates taking turns between two players (beginning with Player 1), placing a marker during each turn.
    - Evaluates the board for a winner after each placement.
    - Continues the game until one player wins (returning 1 or 2 to reflect the winning player), or the game is a draw (returning -1).
- Call play_game 1000 times, and store the results of the game in a list called `results`.

While Loop is used to execute a block of statements repeatedly until a given condition is satisfied. And when the condition becomes false, the line immediately after the loop in the program is executed.

The break statement in Python terminates the current loop and resumes execution at the next statement

In [22]:
# their answer

random.seed(1)

def play_game():
    board = create_board()
    winner = 0
    while winner == 0: # as long as there is no winner, meaning that a winner has not been assigned 
        for player in [1, 2]: # alternates player 1, 2, 1, 2
            random_place(board, player) # randomly place player on board
            winner = evaluate(board) # reassigns winner to winner given by the evaluate function
            if winner != 0: # once winner is assgined and winner does not longer equal zero
                break # stops the while loop
    return winner

results = [play_game() for i in range(1000)]
results.count(1)

591

In [23]:
random.seed(1)

# write your code here! 

def play_game():
    board = create_board()
    while True:
        for player in [1, 2]:
            random_place(board, player)
            result = evaluate(board)
            if result != 0:
                return result   
# plays the games one time


In [24]:

games = 1000
result = []

for i in range(games):
    result.append(play_game())
    
result

[1,
 2,
 1,
 2,
 -1,
 -1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 -1,
 1,
 1,
 2,
 1,
 1,
 -1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 -1,
 2,
 1,
 2,
 1,
 -1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 -1,
 1,
 1,
 2,
 2,
 -1,
 1,
 -1,
 2,
 1,
 -1,
 1,
 1,
 2,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 -1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 -1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 -1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 -1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 2,
 2,
 1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 2,
 1,
 -1,
 -1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 2,
 -1,
 2,
 1,
 2,
 1,
 -1,
 1,
 -1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 1,

In [25]:
result.count(1)

591

#### Exercise 11

In the previous exercise, we see that when guessing at random, it's better to go first, as expected. Let's see if Player 1 can improve their strategy. 

#### Instructions 
- Create a function `play_strategic_game()`, where Player 1 always starts with the middle square, and otherwise both players place their markers randomly.
- Call `play_strategic_game` 1000 times.

In [ ]:
board, winner = create_board(), 0

# is the same as 

board = create_board()
winner = 0


In [23]:
random.seed(1)

# write your code here
def play_strategic_game():
    board, winner = create_board(), 0 # simply reassigns values
    board[1,1] = 1 # makes player number 1 go first and makes him play on the middle square
    while winner == 0:
        for player in [2,1]: # makes player begin, since player one already played
            board = random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner    


ITERATIONS = 1000
result2 = []
for i in range(ITERATIONS):
    result2.append(play_strategic_game())
    
result2.count(1) 

716

In [ ]:
# Their answer

          random.seed(1)

def play_strategic_game():
    board, winner = create_board(), 0
    board[1,1] = 1
    while winner == 0:
        for player in [2,1]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

results = [play_strategic_game() for i in range(1000)]
results.count(1)
716
        